### ISSUE TITLE
Remove QLogo / QiskitLogo component

### ISSUE THREAD

**Issue by eddybrando** [qiskit-community/qiskit-vue#16]
This component might be replaced by a regular SVG file.

We should investigate further to see if there is any reason currently applicable that might suggest otherwise.

**Comment by eddybrando** [comment]
@y4izus, @vabarbosa: Is there a reason why the Qiskit logo in Qiskit.org and Platypus is a Vue component and not just an SVG?

I guess there might be a historical reason, but does it make sense to keep having a whole Vue component instead of a single image file?

FYI @abdonrd

**Comment by vabarbosa** [comment]
i am not aware of any reason why it is or has to be a Vue component (perhaps it is historical).
i am in favor or replacing with an SVG

**Comment by abdonrd** [comment]
Yeah, totally agree! I'm in favor if replacing with an SVG.

**Comment by y4izus** [comment]
Could you elaborate more why you think is better to have directly an SVG rather than a component with and SVG inside?

**Comment by eddybrando** [comment]
> Could you elaborate more why you think is better to have directly an SVG rather than a component with and SVG inside?

I think the main arguments would be:

1. Faster loading time of just an image in comparison to a Vue component.
2. No dependency on a JS framework to start before being rendered.
3. Less JS shipped to the client.
4. Less complexity.

**Comment by y4izus** [comment]
Makes totally sense, I'm also in favor of replacing it with an SVG :)
